// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABkq6pvNvs7jDBeLr7-cH5pLmBT32Zk80',
    appId: '1:647959089753:android:4fd7d6f9f8e853119e5748',
    messagingSenderId: '647959089753',
    projectId: 'user-notes-flutter',
    storageBucket: 'user-notes-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDflp-mUjlD5AW4OmOi5uEidsR9VVwhokI',
    appId: '1:647959089753:ios:ae12e3b7274438159e5748',
    messagingSenderId: '647959089753',
    projectId: 'user-notes-flutter',
    storageBucket: 'user-notes-flutter.appspot.com',
    iosClientId: '647959089753-jggcsfjbdqchesn4ri7e2n93fvb9k0rp.apps.googleusercontent.com',
    iosBundleId: 'com.example.notes',
  );
}
